

  spring:
    datasource:
      username: root
      password: mahmoud
      url: jdbc:mysql://localhost:3306/hotel_db
      driver-class-name: com.mysql.cj.jdbc.Driver



    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true


    servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB
        file-size-threshold: 2KB
  server:
    port: 9192


